FROM node:19-alpine

# ARGS
ARG PAYMENT_PRIVATE_KEY
ARG PAYMENT_PUBLIC_KEY
ARG PAYMENT_URL
ARG MODE_DEV
ARG PAYMENT_INTEGRITY_SECRET

# ENVS
ENV PAYMENT_PRIVATE_KEY=${PAYMENT_PRIVATE_KEY}
ENV PAYMENT_PUBLIC_KEY=${PAYMENT_PUBLIC_KEY}
ENV PAYMENT_URL=${PAYMENT_URL}
ENV MODE_DEV=${MODE_DEV}
ENV PAYMENT_INTEGRITY_SECRET=${PAYMENT_INTEGRITY_SECRET}

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json"]
ADD ./ /usr/src/app/

RUN npm install

CMD npm run start